<?php
define('LA_HOME','Trang chủ');
define('LA_ABOUT_US','Giới thiệu');
define('LA_PRODUCT','Sản phẩm');
define('LA_SERVICE','Dịch vụ');
define('LA_NEWS','NEWS');
define('LA_VIDEO_CLIP','Video Clip');
define('LA_HOT_NEWS','Tin nổi bật');
define('LA_PARTNER','Đối tác');
define('LA_ESTATE_GUIDE','Cẩm nang nhà đất');
define('LA_JOB','Tuyển dụng');
define('LA_ESTATE_SELL','BDS - Cần  bán');
define('LA_ESTATE_LEASE','BDS - Cho thuê');
define('LA_ESTATE_BUY','BDS - Cần  mua');
define('LA_ESTATE_RENT','BDS - Cần thuê');
define('LA_CATEGORY','Danh mục');
define('LA_GOLDEN_PRICE','Giá vàng');
define('LA_EXCHANGE_RATE','Tỷ giá');
define('LA_TYPE','Loại');
define('LA_BUY','Mua');
define('LA_SELL','Bán');
define('LA_TERM','Điều kiện sử dụng');
define('LA_CONDITION','Điều khoản thỏa thuận');
define('LA_DATE','Ngày');
define('LA_BRIEF_CONTENT','Nội dung tóm tắt');
define('LA_DISTRICT','Quận/Huyện');
define('LA_ESTATE_TYPE','Loại bất động sản');
define('LA_SELECT_ONE','Chọn một');
define('LA_PROVINCE','Tỉnh/Thành phố');
define('LA_PRICE','Giá');
define('LA_AREA','Diện tích');
define('LA_FROM','Từ');
define('LA_TO','Đến');
define('LA_MILLION','Triệu');
define('LA_PROPERTY_FEATURES','Đặc điểm bất động sản');
define('LA_ADDRESS','Địa chỉ');
define('LA_DESCRIPTION','Mô tả');
define('LA_POST_DATE','Ngày đăng tin');
define('LA_NUM_FLOOR','Số tầng');
define('LA_INTERIOR','Nội thất');
define('LA_DIRECTION','Hướng nhà');
define('LA_DIRECTION_BANCONY','Hướng ban công');
define('LA_FRONT','Mặt tiền');
define('LA_ROAD','Mặt đường');
define('LA_NUM_BEDROOM','Số phòng ngủ');
define('LA_NUM_TOILET','Số toilet');
define('LA_ESTATE_IMAGE','Ảnh bất động sản');

define('LA_CONTACT','Liên hệ');
define('LA_NO_ITEM','Chưa có sản phẩm');
define('LA_ORDER_BY','Sắp xếp theo');
define('LA_ORDER_BY_NAME','Tên sản phẩm');
define('LA_ORDER_BY_PRICE_UP','Giá tăng dần');
define('LA_ORDER_BY_PRICE_DOWN','Giá giảm dần');
define('LA_HOT_PRODUCT','Sản phẩm nổi bật');
define('LA_NEW_PRODUCT','Sản phẩm mới đăng');


define('LA_INPUT_KEYWORD','Từ khóa không được để trống và phải dài hơn 2 ký tự');
define('LA_TURN_ON_OFF_LANGUAGE','Bật/Tắt bộ gõ tiếng Việt');
define('LA_HOTNEWS','Tin nổi bật');
define('LA_SUPPORT','Hỗ trợ trực tuyến');
define('LA_SOURCE','Theo');
define('LA_NEWSEST','Newest');
define('LA_OLDNEWS','The article was published');
define('LA_CONTACT_FULLNAME','Họ và Tên');
define('LA_CONTACT_ADDRESS','Địa chỉ');
define('LA_CONTACT_PHONE','Điện thoại');
define('LA_CONTACT_FAX','Fax');
define('LA_CONTACT_MOBILE','Di động');
define('LA_CONTACT_EMAIL','Email');
define('LA_CONTACT_TITLE','Tiêu đề');
define('LA_CONTACT_CONTENT','Nội dung');
define('LA_CONTACT_SENT_SUCCESS','Gửi liên hệ thành công!');
define('LA_CONTACT_NOTE','Thông tin khác');
define('LA_VIEW_ALL','Xem thêm');
define('LA_SEARCH_RESULT','Kết quả tìm kiếm');


define('MONEY_UNIT','VNĐ');

define('LA_UP_ER1','Wrong filetype.');
define('LA_UP_ER2','Technical error: File has not been uploaded.');
define('LA_UP_ER3','File is to big. Please reduce the image and try again.');
define('LA_UP_ER4','Could not find a suiteable file ending.');
define('LA_UP_ER5','Could not move the file to storge area. Webmaster: chech permission on image folder.');
define('LA_UP_ER6','ImageProgram ImageMagick or GD failed. Check that it is working.');
define('LA_UP_UNKNOWN','Unknown error. Please try again');

?>